os: windows
language: C++


before_install:
  - choco install python
  - pip install aqtinstall
  - python -m aqt install 5.13.2 windows desktop win64_msvc2017
script:
  - mkdir build
  - cd build
  - setx path "%path%;C:\Qt\5.13.2\msvc2017\bin"
  - set PATH="%PATH%;C:\Qt\5.13.2\msvc2017\bin"
  - cmake -DCMAKE_PREFIX_PATH="C:\Qt\5.13.2\msvc2017" ..
  - cmake --build .
#  - windeployqt ./editor.exe
  - 7z a -tzip editor.zip -r *
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: editor.zip
  on:
    tags: false
    draft: true
